steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/ace-study-396811/go-api/api-image",
        "./backend",
      ]
    options:
      logging: CLOUD_LOGGING_ONLY
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/ace-study-396811/go-api/api-image",
      ]
    options:
      logging: CLOUD_LOGGING_ONLY
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "asia-northeast1-docker.pkg.dev/ace-study-396811/go-api/api-image"
      - "--region"
      - "asia-northeast1"

