version: "3.9"
# ref: https://docs.docker.com/compose/compose-file
services:
  app:
    image: vermelazo
    build:
      args:
        - target=dev
    environment:
      ENV: dev
      PORT: 8080
      DB_HOST: vermelazo
      DB_PORT: 3306
      DB_USER: vermelazo
      DB_PASSWORD: vermelazo
      DB_NAME: vermelazo
      REDIS_HOST: todo-redis
      REDIS_PORT: 6379
    volumes:
      - .:/app
    ports:
      - "18000:8080"
  db:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: vermelazo
      MYSQL_PASSWORD: vermelazo
      MYSQL_DATABASE: vermelazo
    volumes:
      - db-data:/var/lib/mysql
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - "33306:3306"
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "36379:6379"
    volumes:
      - redis-data:/data
volumes:
  db-data:
  redis-data:
